# Generated by Django 5.0.4 on 2024-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='tel',
            field=models.CharField(max_length=100),
        ),
    ]
