# Generated by Django 5.0.4 on 2024-04-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='gone_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
