# Generated by Django 5.0.4 on 2024-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attendance_gone_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='gone_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
